{
  "pipe_parallel_size": 0,
  "model_parallel_size": 0,
  # "make_vocab_size_divisible_by": 1, # thuis param cause cuda index error

  # model settings
  "num_layers": 32,
  "hidden_size": 4096,
  "num_attention_heads": 32,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,

  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "silu",

  # finetuning option
  "finetune": true,

   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",

   # optimizer settings
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.000012,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },
   "min_lr": 0.0000012,

   # batch / data settings
   "train_batch_size": 256,
   "data_impl": "mmap",

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,

   # precision settings
   "fp16": {
     "bf16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "initial_scale_power": 12,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train_iters": -1,
   "lr_decay_iters": 65000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.03,
   "checkpoint_factor": 5000,
   "eval_interval": 1000,
   "eval_iters": 10,

   # logging
   "log_interval": 1,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,

  "train-data-paths": ["data/slimpajama/chunk1_text_document"],
  "valid-data-paths": ["data/slimpajama/chunk1_text_document"],
  "test-data-paths": ["data/slimpajama/chunk1_text_document"],

  "vocab-file": "./tokenizers/llama_tokenizer.model",
  "tokenizer_type": "SPMTokenizer",
  "launcher": "slurm",
  "deepspeed_slurm": true
  "save": "pm:s3://P_model_weights/zengzhiyuan/checkpoints/moefication/llama_7b_e32_postlocal/",
  # "load": "./checkpoints/neox/converted-llama7B-32e",
  "load": "pm:s3://P_model_weights/zengzhiyuan/checkpoints/moefication/llama_7b_e32_postlocal/",
  "load_iteration": 65000,
  "tensorboard-dir": "tensorboard/moefication/llama_7b_e32_postlocal/",
  # "log-dir": "./logs",
  "from_dense_to_moe": {
    "do_convert": false,
    "post": "local"
  },
  "moe_num_experts": 32,
  "ep_world_size": 8,
  "moe_top_k": 1,
  "moe_min_capacity": 0,
  "moe_freq": 2,
  "moe_aux_loss_weight": {
    "load_balance": 0.01,
    "zloss": 0,
    "entropy": 0,
    "kl_div": 0
  }
}