{
  "pipe_parallel_size": 0,
  "model_parallel_size": 0,
  # "make_vocab_size_divisible_by": 1, # thuis param cause cuda index error

  # model settings
  "num_layers": 16,
  "hidden_size": 2048,
  "num_attention_heads": 8,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",

  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": true,

  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  # finetuning option
  "finetune": true,

   # optimizer settings
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.00012,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },
   "min_lr": 0.000012,

   # batch / data settings
   "train_batch_size": 256,
   "gas": 1,
   "data_impl": "mmap",

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,

   # precision settings
   "fp16": {
     "bf16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "initial_scale_power": 12,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train_iters": 20000,
   "lr_decay_iters": 20000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.1,
   "checkpoint_factor": 5000,
   "eval_interval": 500,
   "eval_iters": 10,

   # logging
   "log_interval": 1,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,

  "train-data-paths": ["data/pile_00/pile_00_neox_tokenizer_text_document"],
  "valid-data-paths": ["data/pile_00/pile_00_neox_tokenizer_text_document"],
  "test-data-paths": ["data/pile_00/pile_00_neox_tokenizer_text_document"],

  "vocab-file": "data/tokenizers/20B_tokenizer.json",
  "tokenizer_type": "HFTokenizer",
  "launcher": "slurm",
  "deepspeed_slurm": true
  "save": "s3://P_model_weights/zengzhiyuan/checkpoints/dense/pythia1b_finetune_pile00/",
  "load": "./checkpoints/pythia-1b/",
  "load_iteration": 0,
  "tensorboard-dir": "tensorboard/dense/pythia1b_finetune_pile00/",
  "log-dir": "./logs",
}